# Generated by Django 3.1.6 on 2021-08-05 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='name',
        ),
        migrations.AddField(
            model_name='expense',
            name='description',
            field=models.CharField(default='default description', max_length=200),
        ),
        migrations.AddField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='restapi.group'),
        ),
        migrations.AddField(
            model_name='expense',
            name='total_amount',
            field=models.IntegerField(default=1000),
        ),
        migrations.AddField(
            model_name='expense',
            name='users',
            field=models.ManyToManyField(to='restapi.UserExpense'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restapi.category'),
        ),
        migrations.DeleteModel(
            name='Ledger',
        ),
    ]
