# Generated by Django 3.1.6 on 2021-08-06 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpense',
            old_name='users',
            new_name='user',
        ),
    ]
