# Generated by Django 3.1.6 on 2021-08-05 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='owner',
        ),
    ]
