# Generated by Django 3.1.6 on 2021-08-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0002_auto_20210806_1927'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='total_amount',
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
