# Generated by Django 3.1.6 on 2021-08-05 17:09

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('restapi', '0003_auto_20210805_1647'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpense',
            old_name='amount_lent',
            new_name='paid',
        ),
        migrations.RenameField(
            model_name='userexpense',
            old_name='amount_owed',
            new_name='share',
        ),
    ]
