# Generated by Django 3.1.6 on 2021-08-05 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_auto_20210805_1709'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='users',
            new_name='members',
        ),
        migrations.RenameField(
            model_name='userexpense',
            old_name='paid',
            new_name='amount_lent',
        ),
        migrations.RenameField(
            model_name='userexpense',
            old_name='share',
            new_name='amount_owed',
        ),
    ]
