# Generated by Django 3.1.6 on 2021-08-05 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20210805_1757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='users',
        ),
        migrations.RemoveField(
            model_name='userexpense',
            name='name',
        ),
        migrations.AddField(
            model_name='userexpense',
            name='expense',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='restapi.expense'),
        ),
    ]
