# Generated by Django 3.1.6 on 2021-08-05 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0007_auto_20210805_1814'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userexpense',
            old_name='users',
            new_name='user',
        ),
    ]
