name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  app-tagname:  # id of input
    description: 'tag of the app container'
    required: true
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'django.Dockerfile'
  args:
    - ${{ inputs.app-tagname }}